const recommendationForUnderWeight = `If your BMI is underweight, it's important to take steps to gain weight in a healthy way. Incorporating more calorie-dense foods such as nuts, seeds, nut butter, avocado, olive oil, and cheese into your diet, and increasing your portion sizes can help you consume more calories. Eating smaller, more frequent meals throughout the day and adding a healthy snack such as a smoothie, yogurt, or fruit in between your meals can also help you consume more calories. Additionally, it's important to choose nutrient-dense foods such as lean meats, fish, whole grains, fruits, and vegetables to ensure that you're gaining healthy weight. You can also consider a weight gain supplement under the guidance of a healthcare professional. Regular exercise can help you build muscle mass, which will increase your weight. Make sure you're getting enough sleep and reduce stress in your life. It is important to consult with a dietitian or healthcare professional to make sure you're on the right track.`

const recommendationForNormalWeight = `Maintaining a healthy weight is important and if your BMI is within the normal range, it's important to continue to make healthy choices. Eating a balanced diet that includes a variety of fruits, vegetables, whole grains, lean proteins, and healthy fats is important to provide your body with the necessary nutrients it needs. It's also important to control portion sizes to ensure you're consuming the right amount of food for your body. Regular physical activity is another key component to maintaining a healthy weight. Find a form of exercise that you enjoy and make it a regular part of your routine. Managing stress levels can also play a role in weight management, so consider incorporating stress-reduction techniques such as yoga, meditation or deep breathing. To maintain a healthy weight, it's also important to get enough sleep and stay hydrated by drinking enough water throughout the day. Remember, it's not just about weight, it's also about overall health, so make sure to consult with a healthcare professional if you have any concerns.`

const recommendationForOverWeight = `If your BMI is in the overweight range, it's important to take steps to lose weight in a healthy way. Losing weight slowly and steadily, around 1-2 pounds per week, is the most effective way to lose weight and keep it off. One way to do this is by reducing your daily calorie intake by 500-1000 calories. This can be achieved by making simple changes such as cutting back on sugary drinks, eating smaller portion sizes, and choosing healthier options when eating out.

Incorporating regular physical activity into your routine is also essential for weight loss. Aim for at least 30 minutes of moderate-intensity activity, such as brisk walking, cycling, or swimming, on most days of the week. Resistance training, such as weight lifting, can also help you build muscle and boost your metabolism.

It's also important to focus on making sustainable lifestyle changes rather than short-term fad diets. Consulting a dietitian or healthcare professional can provide you with personalized recommendations based on your specific needs and goals. Additionally, Managing stress levels can also play a role in weight management, so consider incorporating stress-reduction techniques such as yoga, meditation or deep breathing. Remember, losing weight is not just about the number on the scale, it's also about overall health, so make sure to consult with a healthcare professional if you have any concerns.`

const recommendationForObese = `If your BMI is in the obese range, it's important to seek guidance from a healthcare professional as soon as possible. Being obese puts you at a higher risk for a number of serious health conditions such as type 2 diabetes, heart disease, high blood pressure, and sleep apnea. Your healthcare provider can provide you with a personalized plan to help you lose weight in a healthy and sustainable way.

In addition to the tips mentioned earlier such as reducing calorie intake, increasing physical activity, and making sustainable lifestyle changes, it's also important to consider seeking professional help such as a registered dietitian or a certified personal trainer. Additionally, some people may benefit from weight loss medications, bariatric surgery or other medical interventions under the guidance of a healthcare professional.

It's also important to remember that weight loss should not be the only focus, improving overall health should be the ultimate goal. Therefore it's important to work with a healthcare professional to monitor and manage any related health condition and to make sure that you are losing weight in a healthy way.`